### ISSUE TITLE
用了  av-weapp-min.js 后出现以下错误

### ISSUE THREAD

**Issue by kungfu-software** [leancloud/leantodo-weapp#6]
用了  av-weapp-min.js 后出现以下错误

Maximum call stack size exceeded;at "pages/todos/todos" page addTodo function
RangeError: Maximum call stack size exceeded
    at Function._.isObject (http://189926361.appservice.open.weixin.qq.com/utils/leancloud-storage.js:249:20)
    at Object.AV._decode (http://189926361.appservice.open.weixin.qq.com/utils/leancloud-storage.js:581:41)
    at http://189926361.appservice.open.weixin.qq.com/utils/leancloud-storage.js:582:750
    at http://189926361.appservice.open.weixin.qq.com/utils/leancloud-storage.js:598:104
    at Function._.each._.forEach (http://189926361.appservice.open.weixin.qq.com/utils/leancloud-storage.js:52:161)
    at Object.AV._objectEach.AV._each (http://189926361.appservice.open.weixin.qq.com/utils/leancloud-storage.js:598:73)
    at Object.AV._decode (http://189926361.appservice.open.weixin.qq.com/utils/leancloud-storage.js:582:706)
    at http://189926361.appservice.open.weixin.qq.com/utils/leancloud-storage.js:582:750
    at http://189926361.appservice.open.weixin.qq.com/utils/leancloud-storage.js:598:104
    at Function._.each._.forEach (http://189926361.appservice.open.weixin.qq.com/utils/leancloud-storage.js:52:161)

**Comment by kungfu-software** [comment]
更新了所有的reference 到av-weapp-min.js   问题解决了
